server:  port: 4040   

spring:  application:    name: customer-service
    

eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://eureka-peer1:8765/eureka
  instance:    prefer-ip-address: true  