spring:
  config:
    activate:
      on-profile:
      - dev
 
server:  port: 5050
  
logging:  level:    '[org.springframework.boot]': debug        
    
---

spring:
  config:
    activate:
      on-profile:
      - prod
 
server:
  port: 5055
  
logging:
  level:
    '[org.springframework.boot]': info        
    